### ISSUE TITLE
Null reference exception when closing a world that has not been opened with Ngrok LAN [BUG]

### ISSUE THREAD

**Issue by Flooflez** [Alujjdnd/Ngrok-LAN#17]
**Describe the bug**
Null reference exception when closing a world that has not been opened with Ngrok LAN

**To Reproduce**
1. Open a world
2. Close the world

**Expected behavior**
No error is thrown

**Comment by Alujjdnd** [comment]
This bug has been solved in [Release 1.4.3](https://github.com/Alujjdnd/Ngrok-LAN/releases/tag/1.4.3)! Thank you so much for pointing this out! 😊
