### ISSUE TITLE
[BUG] Friend Unable to Connect to Server

### ISSUE THREAD

**Issue by bufothefrog** [Alujjdnd/Ngrok-LAN#22]
**Describe the bug**
Friend cannot connect to my Ngrok-LAN world and gets an error message.

**To Reproduce**
1. Attempt to connect to my Ngrok-LAN world

**Expected behavior**
The friend connects and is able to play the game.

**Screenshots**
![issue](https://user-images.githubusercontent.com/80820565/176421454-4fd12317-d3ef-4cdd-a9f0-302c6f729fce.png)

**Desktop (please complete the following information):**
 - OS: Fedora 36
 - Minecraft Version 1.19
 - Ngrok-LAN Version 1.4.4

**Additional context**
I am using a VPN, could that be the cause?

**Comment by Flooflez** [comment]
Have you tried to recreate this bug without the VPN? 

Also this specific error message does not seem to be unique to Ngrok LAN servers, as seen in [MC-95529](https://bugs.mojang.com/browse/MC-95529).

Are you running any other mods along side Ngrok LAN? Perhaps it is some kind of mod incompatibility. 

Additionally, though I haven't tested this, I am aware of a mod called [Connectivity](https://www.curseforge.com/minecraft/mc-mods/connectivity) that supposedly fixes "packet size exceptions during login/play"

**Comment by Flooflez** [comment]
There has not been an update in this thread for a while so I will mark this as resolved.
