### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by VenomousReaperGoat** [Alujjdnd/Ngrok-LAN#26]
**Describe the bug**
MAking any player an OP or just starting the server with cheat enabled kicks everyone
**To Reproduce**
1. Go to 'menu '
2. Click on 'the button to start lan server in the main menu'
3. then 'change mode to creative and start lan'
4. give op using /op

**Expected behavior**
I expected him to just easily become op and instabuild in my testing map with litematica...

**Screenshots**
![image](https://user-images.githubusercontent.com/85793899/202928742-f7da3aad-5f44-43ce-98cd-a9bf5ac830d5.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 Pro
 - Minecraft Version 1.19.2
 - Ngrok-LAN Version 1.4.4

**Additional context**
We were trying to use litematica to paste a whole schematic, but he kept getting kicked for spamming

**Comment by Flooflez** [comment]
That's strange, could he run any other commands like /gamemode?
This might be an incompatibility with Litematica, but it's weird that he gets kicked for spamming. 

Could I also get a modlist to see what other mods you're running?

**Comment by Flooflez** [comment]
Accidentally closed

**Comment by VenomousReaperGoat** [comment]
> That's strange, could he run any other commands like /gamemode? This might be an incompatibility with Litematica, but it's weird that he gets kicked for spamming.
> 
> Could I also get a modlist to see what other mods you're running?

Not sure if he could, he probably cant because he gets kicked everytime hes made an op, and i dont think youll like what you are about to see....MY MODLIST!

![image](https://user-images.githubusercontent.com/85793899/202931975-3b508b7b-c11c-4d54-8297-65e3b2e4788c.png)
![image](https://user-images.githubusercontent.com/85793899/202932003-30faabc0-58cb-453a-a308-227b7777336a.png)

Anyways, if you want me to try it after removing any mods, let me know. I would love to test stuff to make this mod even a lil better for everyone.

**Comment by Flooflez** [comment]
That's a lot of mods so it might take me some time to comb through it, I'm not sure if I'll be able to fix this asap but I'll try.
(Also why is Moar FPS on this lol)

Just to clarify, your friend immediately gets kicked for spamming when opped? That's super strange, and it really makes me think it's a result of some weird interaction with another mod. My immediate senses draw me to NotifMod and Bad Packets, but I need to do some testing. 

Are there any mods that change Vanilla behavior (like adding content and stuff not just utility or optimisations)?

Also, if you still have it, could you upload the log of when your friend got kicked?

**Comment by VenomousReaperGoat** [comment]
So uh, its 6 am here... Ill reply back here if it stays open after 5
hours.. I feel too sleepy to do anything atm, sorry.

Also, ill let you know that he gets kicked for spamming when he tries
pasting a schematic into the world and insta building it. However i dont
know what error he got when he got kicked whenever i turned him into an op.
Ill try repeating this with him and let you know what it says for him and
also send the log of that moment.


Sorry for this 6 hour delay.
Also if theres like a discord server i could join or something, do let me
know.

**Comment by Flooflez** [comment]
No problem, take your time

**Comment by VenomousReaperGoat** [comment]
(Also, we dont talk about Moar FPS....)

**Comment by VenomousReaperGoat** [comment]
So uh, sorry for the 22-hour delay but I've got information...

So, uh other than Xaeros minimap adding a minimap, I'm pretty sure there's nothing that adds stuff into vanilla...

And I've done some tests, and got 2 error messages for you

https://cdn.discordapp.com/attachments/870964223256199208/1044347244729606144/IMG20221121212211.jpg
this is the error that happens when I make him an op (or start world with cheats [probably])


https://cdn.discordapp.com/attachments/870964223256199208/1044347244729606144/IMG20221121212211.jpg
This one happens when Hes trying to paste a schematic in the world directly world with litematica.
Yesterday however, he was getting a message that said something about getting kicked for spamming, but we couldn't recreate that unfortunately.


Hope this broken information helps.
And sorry for the images being in discord and in bad quality. He can't use discord while in minecrack.

**Comment by VenomousReaperGoat** [comment]
anyone alive?

**Comment by Flooflez** [comment]
Apologies, I've been busy with uni but as winter break is coming up I'll have more time to investigate.

Thank you for following up with the crash message, here's something weird I could find:
https://bugs.mojang.com/browse/MC-135110

Does your friend happen to have a texture pack installed?

**Comment by VenomousReaperGoat** [comment]
Hey, thanks for getting back to me. Ill be starting uni very soon so uh,
thos feels very concerning...
Anyways, my friend uses no resource packs whatsoever. However, i have been
using a few resourcepacls, like continuity, dark mode and fresh animations
iris fork.

**Comment by Flooflez** [comment]
Ok after some investigation it seems like this may not be our mod that's directly causing this issue.

Is your friend using an official version of Minecraft (i.e. not a cracked account and vanilla launcher)?

In any case, try delete the assert folder in the .minecraft folder and then regenerating it by running the game again from the official launcher.

**Comment by Flooflez** [comment]
Hi, I'm going to close this issue since there hasn't been a reply for a while. Sorry we couldn't figure out what exactly was happening.
