### ISSUE TITLE
[BUG] Crash on 1.19.3

### ISSUE THREAD

**Issue by Zorklis** [Alujjdnd/Ngrok-LAN#27]
**Describe the bug**
Game launches but when pressing open to lan, it crashes the game.

**To Reproduce**
1. Press Open to lan

**Expected behavior**
Should open the lan menu and let users start server

**Comment by Flooflez** [comment]
Could you provide the crash log?

**Comment by Zorklis** [comment]
[crash-2022-12-17_01.42.26-client.txt](https://github.com/Alujjdnd/Ngrok-LAN/files/10250026/crash-2022-12-17_01.42.26-client.txt)
Thanks for looking at it

**Comment by Flooflez** [comment]
Oh I misread the title. This mod hasn't been updated to 1.19.3 yet. I'll upload the latest version within the next hour.

I will mark this as closed when it has been uploaded

**Comment by Flooflez** [comment]
Hello, I have updated this mod

You may find it now on [Modrinth](https://modrinth.com/mod/ngrok-lan/version/1.4.4-1.19.3) or on Curseforge when the file gets approved (usually takes up to an hour)
