### ISSUE TITLE
Ngrok Tier Info

### ISSUE THREAD

**Issue by Macafry** [Alujjdnd/Ngrok-LAN#3]
Hey, I was browsing modrinth by new and this mod caught my eye. It looks promising!

I would suggest specifying the lowest Ngrok tier necesary to use the mod in the README file. Not everyone is familiar with Ngrok (myselft included) and that little bit of information can help a lot for clueless people like me :P.

**Comment by Alujjdnd** [comment]
Hello,

Thanks for the feedback, I've added this information to the documentation. In summary, a **free Ngrok account** is all you need, and for more information on the workings of Ngrok and how the mod works, please refer to this part of the documentation [here](https://github.com/Alujjdnd/Ngrok-LAN/blob/main/README.md#what-is-ngrok)

If anything needs further clarification, please feel free to open another issue. However for now, I will mark this issue resolved.

Happy playing!
