### ISSUE TITLE
[BUG] Crashes

### ISSUE THREAD

**Issue by DarkestTroller** [Alujjdnd/Ngrok-LAN#31]
When I click 'open public server', the game crashes after the port is loaded.

Ngrok LAN: 1.4.4
Minecraft: 1.19.3
OS: MacOS 13.2.1 (ARM)

The 'connected' message is visible for one second before Minecraft crashes.

**Comment by DarkestTroller** [comment]
Forgot to mention that the Minecraft version is 1.19.3.

**Comment by Flooflez** [comment]
Can you provide a crash log?

**Comment by DarkestTroller** [comment]
![Screenshot 2023-03-08 at 9 05 29 am](https://user-images.githubusercontent.com/62977197/223570131-1103dc04-e17d-4fda-b4d4-2fd944f4a072.png)

Best I can do for now, nothing is written to the 'crash-reports' folder.

**Comment by Flooflez** [comment]
What launcher are you using, and do you have any other mods installed?

**Comment by DarkestTroller** [comment]
I took out the other mods and left only the required mods, but there was no difference, I am using the official launcher.

**Comment by Flooflez** [comment]
I'm sorry but without the log I don't have enough information to determine the issue.
Are you sure there is no other logs available? (I.e in the minecraft folder there is a logs folder, which contains all logs from the game)

**Comment by Flooflez** [comment]
Hi, I'm going to close this issue due to inactivity. Please reopen the issue if necessary.
