### ISSUE TITLE
[F-REQ] End Server Button

### ISSUE THREAD

**Issue by pgain88** [Alujjdnd/Ngrok-LAN#33]
**Is your feature request related to a problem? Please describe.**

Once the server is started, add a function to allow it to be closed. For Example, Closing an Opened Lan server by disabling it in the settings. 

**Describe the solution you'd like**

A button where the "Open Lan" was, turn it into something like "End Server"

**Describe alternatives you've considered**

only other working solution is to end the game and relaunch. 

**Additional context**

**Comment by Flooflez** [comment]
Hi there sorry took so long to reply,
I really like this idea but I'm struggling to find a clean place to put the button.

The Open Lan button now turns into Player Reporting when a Lan world is open.
I'm experimenting with different button positions now and plan on putting this feature will be in the next release for 1.20.1.
If you have any feedback about the button placement that would be very much appreciated.

**Comment by Flooflez** [comment]
Whoops! Forgot to close this.
Feature was added in the latest release for 1.20.1
