### ISSUE TITLE
[BUG] Not compatible with 1.20

### ISSUE THREAD

**Issue by Zorklis** [Alujjdnd/Ngrok-LAN#36]
![image](https://github.com/Alujjdnd/Ngrok-LAN/assets/85455465/06aa20a0-be0f-4ac1-8b0f-caa7a2c60ce1)

**Comment by Flooflez** [comment]
We're gonna skip 1.20 due to its stability, just waiting for cloth config to be released for 1.20.1.
Update to 1.20.1 coming ASAP.

**Comment by Flooflez** [comment]
Hi just to let you know version 1.5.0 for 1.20.1 is out now :)
