### ISSUE TITLE
[BUG] "Close server" button is shown when playing on servers

### ISSUE THREAD

**Issue by TheCatRiX** [Alujjdnd/Ngrok-LAN#39]
**Describe the bug**
"Close server" button is shown even when playing on usual servers. Pressing it crashes the game.

**Screenshots**
![screenshot](https://github.com/Alujjdnd/Ngrok-LAN/assets/58901923/a022c942-0cc3-441c-b058-afcab7e51bd5)

**Desktop:**
 - OS: Windows 11
 - Minecraft Version: 1.20.1
 - Ngrok-LAN Version: Release 1.5.0

**Comment by Flooflez** [comment]
Hi, I should’ve opened this myself, this is already fixed in the next release. You can download the beta build in advance on this GitHub page under releases.

I will close this when the next full release comes out.

**Comment by TheCatRiX** [comment]
Oh, I didn't notice that beta... Ok

**Comment by Flooflez** [comment]
Fixed on latest 1.20.2 release
