### ISSUE TITLE
Can't Start

### ISSUE THREAD

**Issue by Mr-Wolter** [Alujjdnd/Ngrok-LAN#4]
![image](https://user-images.githubusercontent.com/83448525/161436838-3ccf1291-8000-4c95-934c-2d0f276003b2.png)
What should I do?

**Comment by Flooflez** [comment]
hi there, could you more thoroughly describe the process you went through? We're not sure how to fix the issue if we are unable to recreate the bug.

Here are some things you can try in the meantime: 
1. Change your region
2. Regenerate your Auth Token

**Comment by Mr-Wolter** [comment]
> hi there, could you more thoroughly describe the process you went through? We're not sure how to fix the issue if we are unable to recreate the bug.
> 
> Here are some things you can try in the meantime:
> 
> 1. Change your region
> 2. Regenerate your Auth Token

I tried but problem didn't solved :(

**Comment by Alujjdnd** [comment]
If the problem still persists, you could try to update to the newest version [here](https://github.com/Alujjdnd/Ngrok-LAN/releases/tag/1.3.1). (Make sure to delete the old version first)

You may have to input your auth token again in the mod menu after the upgrade.

**Comment by Mr-Wolter** [comment]
> If the problem still persists, you could try to update to the newest version [here](https://github.com/Alujjdnd/Ngrok-LAN/releases/tag/1.3.1). (Make sure to delete the old version first)
> 
> You may have to input your auth token again in the mod menu after the upgrade.

I installed the new version of the mod and tried to put the game in a new directory, created a new token, tried other locations, changed my internet source, checked the necessary mods, but unfortunately I couldn't use it. Same problem again :/

**Comment by Alujjdnd** [comment]
One other possible fix would be restarting your Host Network Service:

1. Press Win+R, type services.msc
2. In the list of services, find "Host Network Service"
3. Right click on it and press restart
4. Try the mod again

**Comment by Mr-Wolter** [comment]
Thanks Its working! :)

**Comment by Mr-Wolter** [comment]
Thanks again 👊🏿
