### ISSUE TITLE
Not A bug But something Important !!

### ISSUE THREAD

**Issue by simploita78** [Alujjdnd/Ngrok-LAN#50]
I have a Minecraft premium account but some of my friends doesnt i just want to ask that if this mod work with my friend's cracked account (Tlauncher) if yes, thank you and sorry for inconvenience, if not then Can you please make it work. simply because whats the point of playing Alone.

I hope you understand.
I appreciate your work.

**Comment by Flooflez** [comment]
I have already answered you question in a previous issue #48
please stop posting the same question

**Comment by simploita78** [comment]
> I have already answered you question in a previous issue #48 please stop posting the same question

oh i am so sorry.. i havent really realised Sorry again !! and thanks
